[repo]
name = 'READMEの表題となるリポジトリ名'
summary = 'READMEに書く概要説明。'
nature_languages = ['en', 'ja', 'en-us']
programming_languages = ['python']
license = 'cc0'
logo = 'docs/logo.png|gif|svg'
demo = 'docs/demo.png|gif|svg'
docs = 'https://...'

[feature]
body = """
* こんな特徴があります
"""

[installation]
windows = ''
mac = ''
linux_debian = 'git python'
linux_fedora = 'git python'
linux_arch = 'git python'
android = ''
body = ''

[requirement]

[note]

[author]

[usage]

[license]

